# Exported from Render on 2025-11-14T21:10:53Z
version: "1"
projects:
- name: Uncharted Lands
  environments:
  - name: Production
    services:
    - type: web
      name: uncharted-lands-server
      runtime: node
      repo: https://github.com/KungRaseri/uncharted-lands-server
      branch: main
      plan: starter
      envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: SENTRY_AUTH_TOKEN
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: HOST
        sync: false
      - key: PORT
        sync: false
      region: oregon
      buildCommand: npm install && tsc
      startCommand: node dist/index.js
      preDeployCommand: npm run db:migrate:run && npm run db:seed
      healthCheckPath: /health
      autoDeployTrigger: commit
      rootDir: .
